=== jrd5136/XML/Recipe/Recipe.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- we defined the root elemet that is Recipes that must contain the child element recipe.-->
<!ELEMENT Recipes (Recipe+)>


<!--enumeration group entity-->
<!ENTITY % types "MainDishes|Desert|Salad">

<!--we created the recipe elementn that include  Title ,Photo, CookTime, Yield, Para, 
                                             Ingredients, Directions, Tips+)-->
 
<!ELEMENT Recipe (Title ,Photo, CookTime, Yield, Para, Ingredients, Directions, Tips+)>
<!ATTLIST Recipe 
          recipe_id  ID #REQUIRED
          recipe_type (%types;) #IMPLIED >

          
<!--  we declared parametr entity which will be used for making PCDATA the content type  -->
<!ENTITY % p "(#PCDATA)" >

<!ELEMENT Title %p; >
<!ELEMENT CookTime %p; >
<!ELEMENT Yield %p;> 
<!ELEMENT Ingredients (Ingredient+) >
<!ATTLIST Ingredients Ingredient_Id IDREF #REQUIRED >
<!ELEMENT Ingredient %p; >


<!ELEMENT Directions (Direction+) > 
<!ATTLIST Directions Direction_Id IDREF #REQUIRED >
<!ELEMENT Direction %p; >
<!ELEMENT Tips  %p; >
<!ELEMENT Para %p; >
<!--<!ELEMENT Photo ANY >-->
 

<!-- we declare a new notation named "JPEG" for the "image/jpeg" type-->
<!NOTATION jpeg SYSTEM "image/jpg">

<!--  we declare an external unparsed entity called "jpeg" that refers to an image file called "Images/Image1.jpg"-->
<!-- to tell the application ther is unparser entity at this location -->
<!ENTITY jpeg SYSTEM "Images/Image1.jpg" NDATA jpeg>

<!-- We create a new attribute of type ENTITY -->
<!ELEMENT Photo EMPTY > 
<!ATTLIST Photo 
          source CDATA #REQUIRED>

=== jrd5136/XML/Recipe/recipe2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="recipe_2.css" ?>
     <!DOCTYPE Recipes SYSTEM "Recipe.dtd" [
<!ENTITY ingre " 
    <Ingredients Ingredient_Id='RCP002'>
    <Ingredient>1 cup quick-cook oats</Ingredient>
    <Ingredient>1/3 cup dried tart cherries</Ingredient>
    <Ingredient>1/2 cup all-natural peanut butter</Ingredient>
    <Ingredient>3 tbsp honey</Ingredient>
    <Ingredient>1 tsp vanilla</Ingredient>
    </Ingredients> " >
    <!ENTITY direct "
 <Directions Direction_Id='RCP002'>
    <Direction> 1) Mix the ingredients together in a bowl.</Direction>
    <Direction> 2) Spread the mixture in a pan and refrigerate for 2 hours.</Direction>
    <Direction> 3) Slice and enjoy! Return uneaten bars to fridge for storage.</Direction>
    </Directions>" > ]>


    <Recipes>
        <Recipe recipe_id="RCP002" recipe_type="Desert">
            <Title>Dr. Oz's No-Bake Energy Bars</Title>
            <Photo source="Images/image6.JPG"/>
            <CookTime> Cook Time: 2 hours </CookTime>
            <Yield> Yield: Makes 5 individual servings</Yield>
            <Para>
                Dr. Oz's no-bake energy bars are designed to help you fight off the mid-day slump! The combination of protein, fiber and antioxidants will stabilize your blood sugar and rev up your energy for hours.
            </Para>
            &ingre; &direct;


            <Tips>
                Eat a serving whenever you need that extra boost!
            </Tips>
        </Recipe>

    </Recipes>

=== jrd5136/XML/Recipe/recipe.xml
<?xml version="1.0" encoding="UTF-8" ?>
<?xml-stylesheet type="text/css" href="recipe_1.css" ?>
    <!DOCTYPE Recipes SYSTEM "Recipe.dtd" [
<!ENTITY ingre " 
    <Ingredients Ingredient_Id='RCP001'>
    <Ingredient>1 12-ounce package frozen raspberries </Ingredient>
    <Ingredient>3/4 cup sugar, divided 1/2 cup and 1/4 cup</Ingredient>
    <Ingredient>1/3 cup water</Ingredient>
    <Ingredient>10 Oreo cookies, without the filling, or 20 chocolate wafer cookies</Ingredient>
    <Ingredient>2 Tbsp melted butter</Ingredient>
    <Ingredient>8 ounces cream cheese, room temperature</Ingredient>
    <Ingredient>Pinch salt</Ingredient>
    <Ingredient>1 egg</Ingredient>
    <Ingredient>1/3 cup sour cream</Ingredient>
    <Ingredient>Whipped cream for topping</Ingredient>
    <Ingredient>Fresh raspberries for garnish</Ingredient>
    <Ingredient>4 Wide-mouthed 8-ounce mason jars</Ingredient>
    </Ingredients> " >
    <!ENTITY direct "
 <Directions Direction_Id='RCP001'>
    <Direction> 1) Set aside 1/2 a cup of the frozen raspberries from the package. With the remaining raspberries, place them in a medium saucepan. Add 1/2 cup sugar and 1/3 cup of water. Bring to a simmer on medium high heat, then lower the heat to maintain the simmer, and gently cook, whisking frequently, until the raspberries have completely broken down, about 10 minutes.</Direction>
    <Direction> 2) If you want, strain the raspberry sauce through a sieve to remove the seeds, and then return the sauce to the pan and continue to gently simmer until the the sauce is syrupy. Set aside to cool.</Direction>
    <Direction> 3) Grind the chocolate cookie wafers (Oreo or other brand) in a food processor, mini chopper, or by placing in a plastic bag and crushing with a rolling pin, until finely ground.</Direction>
    <Direction> 4) Place in a medium bowl and stir in the melted butter. Divide evenly among the mason jars, packing the chocolate crust at the bottom of each mason jar in a layer about 1/4 to 1/3-inch thick.</Direction>
    <Direction> 5) In a mixer, beat the cream cheese on medium speed for 4 minutes, until smooth and light. Add 1/4 cup of sugar and beat 4 minutes more. Add a pinch of salt and the egg, and beat another minute.</Direction>
    <Direction> 6) Place the reserved raspberries on top of the chocolate crusts in the mason jars in a single layer. Pour the raspberry cheesecake filling over the raspberries in the jars.</Direction>
    <Direction> 7) 5 Place in a roasting pan and add about an inch of boiling water to the pan to create a water bath, which will help the cheesecakes cook more evenly. Bake at 325°F for 40 minutes. Then turn off the heat in the oven and let the cheesecakes continue to gently cook in the residual heat of the oven for another 30 minutes. </Direction>
    <Direction> 8) Remove from oven and let cool to room temp. Chill for at least a half hour before eating. Don't worry if there are cracks on the surface of the cheesecakes. Top with the remaining raspberry sauce, whipped cream, and fresh raspberries.</Direction>
    </Directions>" > ]>


    <Recipes>
        <Recipe recipe_id="RCP001" recipe_type="Desert">
            <Title>Raspberry Cheesecake</Title>
            <Photo source="Images/Image1.jpg" />
            <CookTime> Cook Time: 2 hours </CookTime>
            <Yield> Yield: Makes 4 individual servings</Yield>
            <Para> As soon as you think you want to make these cheesecakes, take the cream cheese out of the refrigerator to help it soften as it warms to room temperature. You can probably easily double the recipe without having to double the raspberry sauce.</Para>
            &ingre; &direct;


            <Tips>No need to water bath the crust, the purpose of baking the crust is to harden it so it stays separate from the cheesecake filling when you pour it into the jars. If you bake it with a water bath you won’t harden the crust, but will have the opposite effect.
            </Tips>
        </Recipe>

    </Recipes>

=== jrd5136/XML/Recipe/recipe3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="recipe_3.css" ?>
<!DOCTYPE Recipes SYSTEM "Recipe.dtd"
[
<!ENTITY ingre " 
    <Ingredients Ingredient_Id='RCP003'>
        <Ingredient>2 and 1/2 cups grated organic carrots </Ingredient>
        <Ingredient>2 and 1/2 cups almond milk</Ingredient>
        <Ingredient>8 tbsp organic unrefined cane sugar </Ingredient>
        <Ingredient>1/4 or 1/3 cup almond paste or evaporated milk</Ingredient>
        <Ingredient>5-6 cardamom, powdered or crushed</Ingredient>
        <Ingredient>8-10 unsalted whole or chopped cashews</Ingredient>
        <Ingredient>7-8 unsalted pistachois - sliced or chopped</Ingredient>
        <Ingredient>12-15 golden raisins</Ingredient>
        <Ingredient>a pinch of saffron (optional)</Ingredient>
        <Ingredient>2 or 2/12 tbsp neutral flavored oil (sunflower oil)</Ingredient>
     </Ingredients> "
      >
<!ENTITY direct "
 <Directions Direction_Id='RCP003'>
    <Direction> 1) wash, peel and grate the carrots.</Direction>
    <Direction> 2) mix the almond milk or regular dairy milk and grated carrot together in a pan.</Direction>
    <Direction> 3) keep on fire and allow the mixture to simmer.</Direction>
    <Direction> 4) continue to simmer and cook stirring in between.</Direction>
    <Direction> 5) after 15-20 minutes add cardamom powder and stir.</Direction>
    <Direction> 6) when the mixture has started thickening, add sugar and oil.</Direction>
    <Direction> 7) stir and continue to cook.  </Direction>
    <Direction> 8) when the mixture has almost dried, add the almond paste and dry fruits.</Direction>
    <Direction> 9) stir and cook further for 2-3 minutes </Direction>   
    <Direction> 10) serve carrot halwa hot or warm </Direction>
   
   </Directions>"
    >
    ]>   
<Recipes >
    <Recipe recipe_id="RCP003" recipe_type="Desert">
        <Title>Halwa</Title>
        <Photo source="Images/halwa3.JPG"/>
        <CookTime> Cook Time: 40 mins  </CookTime>         
        <Yield>  Yield: Makes 4 individual servings</Yield>
        <Para> carrot halwa - a classic indian dessert made with grated carrots and milk.</Para>
        &ingre;
        &direct;      
        <Tips>
            Please do not indulge in any other activity while cooking, as over cooking spoils the taste!
        </Tips>
    </Recipe>
</Recipes>
